on: [push, repository_dispatch]

env:
  GROUP_ID: com.octokat.app
  ARTIFACT_ID: install-octokat-app
  VERSION: 1.0-SNAPSHOT
  CLASS_NAME: InstallApp
  TARGET_GROUP_ID: com.octokat.app
  TARGET_ARTIFACT_ID: octokat-app
  TARGET_VERSION: 1.0-SNAPSHOT
  TARGET_CLASS_NAME: PublishApp

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add ${{ env.CLASS_NAME }}.java file
        run: |
          SOURCE_PATH=src/main/java/$(echo ${{ env.GROUP_ID }} | tr . /)
          mkdir -p $SOURCE_PATH
          cat <<- END > $SOURCE_PATH/${{ env.CLASS_NAME }}.java
          package ${{ env.GROUP_ID }};

          import ${{ env.TARGET_GROUP_ID }}.${{ env.TARGET_CLASS_NAME }};

          public class ${{ env.CLASS_NAME }}
          {
              public static void main( String[] args )
              {
                  ${{ env.TARGET_CLASS_NAME }}.main( new String[0] );
              }
          }
          END

      - name: Install packages
        run: mvn install --no-transfer-progress

      - name: Exec package
        run: mvn exec:java -D exec.mainClass=${{ env.GROUP_ID }}.${{ env.CLASS_NAME }} --no-transfer-progress
